version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

